[package]
name = "poussière"
version = "0.1.0"
authors = ["Lucas A. <game4allyt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.2.0"
winit = "0.23.0"
rand = "0.7.3"